name: blogapp
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.7+3  # Updated version
  share: ^2.0.4           # Use a compatible version
  file_picker: ^5.2.1     # Added dependency for picking files
  url_launcher: ^6.1.9    # Added dependency for launching URLs

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
